// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/hovanhoa/ent-blog/ent/runtime.go

const (
	Version = "v0.12.5-0.20231017103211-5718c3001b17"           // Version of ent codegen.
	Sum     = "h1:gd6TrqpkBfBBFLi8YPLI6FSiAIpc8z5EFaptnDqrWpE=" // Sum of ent codegen.
)
